call LFGTest ..\DISKS\CLASSICS MANIAC_A XXX MANIAC ..\INSTALL\MANIAC
call LFGTest ..\DISKS\CLASSICS ZAK____A XXX ZAK ..\INSTALL\ZAK
call LFGTest ..\DISKS\CLASSICS LOOM___A XXX LOOM ..\INSTALL\LOOM
call LFGTest ..\DISKS\CLASSICS INDY___B XXX INDY ..\INSTALL\INDY
call LFGTest ..\DISKS\CLASSICS MONKEY_E XXX MONKEY ..\INSTALL\MONKEY
call LFGTest ..\DISKS\INDY4 PCVIQA_A ND4 ATLANTIS ..\INSTALL\ATLANTIS
call LFGTest ..\DISKS\ND4ESP PCVIQA_A ND4 INDY4ESP ..\INSTALL\INDY4ESP
call LFGTest ..\DISKS\MI2ESP PCV10__A MI2 MONKEY2E ..\INSTALL\MONKEY2E



