call LFGTest ..\DISKS\CLASSICS MANIAC_A XXX MANIAC
call LFGTest ..\DISKS\CLASSICS ZAK____A XXX ZAK
call LFGTest ..\DISKS\CLASSICS LOOM___A XXX LOOM
call LFGTest ..\DISKS\CLASSICS INDY___B XXX INDY
call LFGTest ..\DISKS\CLASSICS MONKEY_E XXX MONKEY
call LFGTest ..\DISKS\INDY4 PCVIQA_A ND4 ATLANTIS
call LFGTest ..\DISKS\ND4ESP PCVIQA_A ND4 INDY4ESP
call LFGTest ..\DISKS\MI2ESP PCV10__A MI2 MONKEY2E

